import jsPDF from "jspdf";
import type { ScanAnalysis } from "@/types/scan";

export function generateReport(result: ScanAnalysis, imageDataUrl?: string) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(10, 10, 10);
  doc.rect(0, 0, pageWidth, 40, "F");
  doc.setTextColor(56, 199, 147);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("BoneScan AI", 14, 18);
  doc.setFontSize(10);
  doc.setTextColor(150, 150, 150);
  doc.text("Medical Scan Analysis Report", 14, 26);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 33);

  let y = 52;

  // Scan image
  if (imageDataUrl) {
    try {
      doc.addImage(imageDataUrl, "JPEG", 14, y, 60, 60);
      y += 68;
    } catch {
      y += 4;
    }
  }

  // Condition & Severity
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(result.condition, 14, y);
  y += 8;
  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(100, 100, 100);
  doc.text(`Severity: ${result.severity}  |  Urgency: ${result.urgency}`, 14, y);
  y += 14;

  const sections = [
    { label: "Affected Region", value: result.affectedRegion },
    { label: "Findings", value: result.findings },
    { label: "Suggested Medication", value: result.medication },
    { label: "Specialist Referral", value: result.doctorType },
    { label: "Additional Notes", value: result.additionalNotes },
  ];

  for (const section of sections) {
    if (!section.value) continue;
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(56, 199, 147);
    doc.text(section.label, 14, y);
    y += 6;
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    const lines = doc.splitTextToSize(section.value, pageWidth - 28);
    doc.text(lines, 14, y);
    y += lines.length * 5.5 + 6;

    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  }

  // Disclaimer
  y += 6;
  doc.setDrawColor(200, 200, 200);
  doc.line(14, y, pageWidth - 14, y);
  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  const disclaimer = "DISCLAIMER: This report is generated by AI and is for informational purposes only. It does not constitute medical advice, diagnosis, or treatment. Always seek the advice of a qualified healthcare provider.";
  const discLines = doc.splitTextToSize(disclaimer, pageWidth - 28);
  doc.text(discLines, 14, y);

  doc.save("BoneScan-AI-Report.pdf");
}
